### PR TITLE
Mip21 no flipper

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by livnev** [comment]
I like this. 😄

**Comment by livnev** [comment]
Looks very good to me!

I have only two questions/suggestions:

- I'm guessing `string doc` instead of `bytes32 doc` is to allow proper IPFS identifiers to be used here? 
- maybe lets bring back the explicit check in `cull` that prevents liquidation of collateral not managed by this liquidation oracle? Even though it's `auth` now this could prevent mistakes

**Comment by brianmcmichael** [comment]
@livnev yes I'd have preferred to use `bytes32` also but I like IPFS even more, as it provides the hash and the content, unfortunately the IPFS hash is too large to fit in the `bytes32` space.

**Comment by gbalabasquer** [comment]
> * maybe lets bring back the explicit check in `cull` that prevents liquidation of collateral not managed by this liquidation oracle? Even though it's `auth` now this could prevent mistakes

Done!

**Review by e18r — APPROVED** [review]

**Review by godsflaw — APPROVED** [review]

**Pull request merged**
