### PR TITLE
MIP21: remove tau and simply add good (true|false)

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by e18r** [comment]
Instead of defining a remediation period, let governance determine whether a loan is in good standing or not by calling `tell` and
`cure`. Calling `cull` won't change the bad standing of a loan.

Furthermore, prevent loans from automatically recovering their good standing after the remediation period has elapsed.

**Comment by gbalabasquer** [comment]
Ignore the list of commits, these should be fine when squashing on merging (if we decide to apply this change).

**Review by godsflaw — APPROVED** [review]

**Comment by livnev** [comment]
Can someone elaborate on the motivation of this PR? I view the ability to keep track of the remeditation period on-chain as a useful feature. Obviously governance has the power to liquidate the position whenever they want but for clarity and correctness I think it's good to have this on-chain process.

**Comment by livnev** [comment]
Please take a look at my comment and changes at PR #14. There was an error in `good` and `cull` which I think is what is being addressed here.

**Comment by e18r** [comment]
Closing in favor of the bug fix introduced in #14.

Actually, I can't close it. @gbalabasquer or @livnev please close this.

**Comment by livnev** [comment]
Closing in favour of #14

**Pull request closed without merging**
