### PR TITLE
Mip21 spell test improvements

### PR DESCRIPTION
**Pull request by e18r**

### CODE REVIEW

**Comment by godsflaw** [comment]
@e18r can you change the base to the `MIP21` branch?

**Comment by e18r** [comment]
@godsflaw done

**Comment by godsflaw** [comment]
Oh, sorry, I mean set the base of the PR on github here:
Screen Shot 2021-02-18 at 11 02 22 AM

**Comment by godsflaw** [comment]
lol, turns out I have the power.
heman

**Review by godsflaw — APPROVED** [review]
This is good for now.

We need to make the `draw()` and `wipe()` tests better in another PR.  We need to ensure there is a `duty` set, that we `hevm.warp()` and `drip()`, and then ensure the tests still work.

**Pull request merged**
